# Generated by Django 3.2 on 2021-09-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_users',
            name='class_list',
            field=models.CharField(choices=[('class5', 'class5'), ('class6', 'class6'), ('class7', 'class7'), ('class8', 'class8'), ('class9', 'class9'), ('class10', 'class10'), ('faculty', 'faculty')], default='class5', max_length=10),
        ),
    ]
